### ISSUE TITLE
Seeding functionality

### ISSUE THREAD

**Issue by matdehaast** [interledger/rafiki#492]
* [ ] Initial support
  * Helper function that can read in a yaml file for peers and accounts

The Seeding will follow the following structure
 ```yaml
peers:
  - asset: USD 
    scale: 2
    liquidity:100000
accounts:
  - name: "Grace Franklin"
    id: 742ab7cd-1624-4d2e-af6e-e15a71638669
    balance: 4000
  - name: "Bert Hamchest"
    id: a9adbe1a-df31-4766-87c9-d2cb2e636a9b
    balance: 4000
  - name: "World's Best Donut Co"
    id: 5726eefe-8737-459d-a36b-0acce152cb90
    balance: 2000
```
